//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aemos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpellResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpellResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aemos.Resources.SpellResources", typeof(SpellResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailySpells.
        /// </summary>
        internal static string DailySpellsComplement {
            get {
                return ResourceManager.GetString("DailySpellsComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	   Id,
        ///	   Name,
        ///	   School,
        ///	   SubSchool,
        ///	   Descriptor,
        ///	   Level,
        ///	   Components,
        ///	   CastingTime,
        ///	   Range,
        ///	   Target,
        ///	   Effect,
        ///	   Area,
        ///	   Duration,
        ///	   SavingThrow,
        ///	   SpellResistance,
        ///	   BriefDescription,
        ///	   MaterialComponents,
        ///	   ArcaneMaterialComponents,
        ///	   XpCost,
        ///	   Focus,
        ///	   ArcaneFocus,
        ///	   BardFocus,
        ///	   ClericFocus,
        ///	   DruidFocus,
        ///	   SorcererFocus,
        ///	   WizardFocus
        ///FROM
        ///	  SpellsCompendium
        ///WHERE 
        ///	  Name LIKE @Name
        ///	  AND Level LIKE @Le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSpellsDetailed {
            get {
                return ResourceManager.GetString("GetSpellsDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Level0, Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9
        ///
        ///FROM @TableName
        ///
        ///WHERE @TableName.CharLevel = @CharacterLevel.
        /// </summary>
        internal static string GetSpellsSlots {
            get {
                return ResourceManager.GetString("GetSpellsSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnownSpells.
        /// </summary>
        internal static string KnownSpellsComplement {
            get {
                return ResourceManager.GetString("KnownSpellsComplement", resourceCulture);
            }
        }
    }
}
