//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aemos.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpellResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpellResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aemos.Resources.SpellResources", typeof(SpellResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DailySpells.
        /// </summary>
        internal static string DailySpellsComplement {
            get {
                return ResourceManager.GetString("DailySpellsComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	   Id,
        ///	   Name,
        ///	   School,
        ///	   SubSchool,
        ///	   Descriptor,
        ///	   Level,
        ///	   Components,
        ///	   CastingTime,
        ///	   Range,
        ///	   Target,
        ///	   Effect,
        ///	   Area,
        ///	   Duration,
        ///	   SavingThrow,
        ///	   SpellResistance,
        ///	   BriefDescription,
        ///	   MaterialComponents,
        ///	   ArcaneMaterialComponents,
        ///	   XpCost,
        ///	   Focus,
        ///	   ArcaneFocus,
        ///	   BardFocus,
        ///	   ClericFocus,
        ///	   DruidFocus,
        ///	   SorcererFocus,
        ///	   WizardFocus
        ///FROM
        ///	  SpellsCompendium
        ///WHERE 
        ///	  Name LIKE @Name
        ///	  AND Level LIKE @Le [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string GetSpellsDetailed {
            get {
                return ResourceManager.GetString("GetSpellsDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Level0, Level1, Level2, Level3, Level4, Level5, Level6, Level7, Level8, Level9
        ///
        ///FROM @TableName
        ///
        ///WHERE @TableName.Id = @CharacterLevel.
        /// </summary>
        internal static string GetSpellsSlots {
            get {
                return ResourceManager.GetString("GetSpellsSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a KnownSpells.
        /// </summary>
        internal static string KnownSpellsComplement {
            get {
                return ResourceManager.GetString("KnownSpellsComplement", resourceCulture);
            }
        }
    }
}
